language: node_js
node_js:
 - "6"
before_deploy:
 - rm -rf .git/
 - rm -rf jasmine/
 - rm -rf node_modules/
 - rm .travis.yml
 - zip -r botato-${TRAVIS_TAG:1}.zip .
deploy:
  - provider: releases
    api_key: "${GITHUB_KEY}"
    file_glob: true
    file: "botato-*.zip"
    skip_cleanup: true
    on:
      tags: true
after_deploy:
 - echo "//registry.npmjs.org/:_authToken=${NPM_KEY}" > ~/.npmrc
 - npm publish
